// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BookEdit: typeof import('./src/components/book/BookEdit.vue')['default']
    BookItem: typeof import('./src/components/book/BookItem.vue')['default']
    ChapterEdit: typeof import('./src/components/chapter/ChapterEdit.vue')['default']
    EditorFooter: typeof import('./src/components/common/editor/EditorFooter.vue')['default']
    Index: typeof import('./src/components/book/Index.vue')['default']
    MenuBar: typeof import('./src/components/common/editor/MenuBar.vue')['default']
    MenuItem: typeof import('./src/components/common/editor/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
